version: 1
labels:
  - label: "automerge"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/build.properties"
      - "project/Versions.scala"
      - "project/plugins.sbt"
  - label: "dependency"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/build.properties"
      - "project/Versions.scala"
      - "project/plugins.sbt"
