version: 1
labels:
  - label: "automerge"
    authors: ["github-actions[bot]"]
    files:
      - "build.sbt"
      - "project/build.properties"
      - "project/Versions.scala"
      - "project/plugins.sbt"
  - label: "dependency"
    authors: ["github-actions[bot]"]
    files:
      - "build.sbt"
      - "project/build.properties"
      - "project/Versions.scala"
      - "project/plugins.sbt"
